SP_LANG = {}
SP_LANG.NoRangeAllSpawn = "Не указан радиус, использую по умолчанию радиус - 500"
SP_LANG.SmallRangeAllSpawn = "Указаный радиус слишком мал, использую по умолчанию радиус - 500"
SP_LANG.DeletedSpawn = "Вы успешно удалили точку спавна."
SP_LANG.NotCreatedSpawn = "Точка не была установлена, что бы её удалять."
SP_LANG.RecoilSpawn = "Осталось ждать %i секунд."
SP_LANG.RecoilSpawn2 = "Вы не можете менять точку спавна чаще чем раз в %i секунд."
SP_LANG.CreatedSpawn = "Вы установили точку спавна."
SP_LANG.NoPermissions = "У вас не достаточно прав для этого."
SP_LANG.DeletedAllSpawn = "Администратор убрал точку спавна для всех игроков."
SP_LANG.CreatedAllSpawn = "Администратор установил точку спавна для всех игроков."
SP_LANG.AttackPlyInSpawn2 = "Вы не можете атаковать игроков которые находятся на спавне."
SP_LANG.AttackPlyInSpawn = "Вы не можете атаковать игроков пока находитесь на спавне."
SP_LANG.SP_enabled = "Spawn Protect активен? (1 = Да ; 0 = Нет)"
SP_LANG.SP_radius = "Радиус, на котором от спавна не возможно стрелять и умирать."
SP_LANG.SP_setspawn = "Разрешить игрокам ставить точки спавна? (1 = Да ; 0 = Нет)"
SP_LANG.SP_recoil = "Сколько нужно ждать, между сменами точек спавна"
SP_LANG.SP_block = "Отключить блокирование пропом на спавне? (1 = Да ; 0 = Нет)"
SP_LANG.PropInPlayer = "У вас в ногах был объект %s, он был удалён."